### ISSUE TITLE
Create a Facebook page and Twitter profile for the news site

### ISSUE THREAD

**Issue by nBorimechkov** [TypiCMS-TeamGamayunSoftUni/Base#23]
Site should have Facebook and Twitter functionality for easier sharing.

**Comment by epaceva** [comment]
[Facebook](http://typi-test.webstars.bg/en) page is created.

**Comment by epaceva** [comment]
Twitter page creation is in progress.

**Comment by epaceva** [comment]
Twitter profile created  - [NewsGamay](https://twitter.com/NewsGamay)
