### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by epaceva** [TypiCMS-TeamGamayunSoftUni/Base#3]
Please work over Introduction
Introduction  
1.1 Purpose 
1.2 Document Conventions  
1.3 Intended Audience and Reading Suggestions  
1.4 Product Scope  
1.5 References

**Comment by epaceva** [comment]
Introduction has been written and agenda corrected to following:
Introduction  
1.1 Purpose and Scope
1.2 Document Conventions
1.3 Intended Audience 
1.4 Overview

The introduction is written and changes saved in main [SRS](https://docs.google.com/document/d/1mw4IskvklVVfYJ9HVqw_l3KUd3rz4hFw_IdMO0uDNPk/edit#)

**Comment by teodornkolev** [comment]
Nice job!
