### ISSUE TITLE
Check new version of SRS

### ISSUE THREAD

**Issue by teodornkolev** [TypiCMS-TeamGamayunSoftUni/Base#5]
I've wrote some new chapters in SRS v0.15. Please make revision.

**Comment by epaceva** [comment]
Confirmed Topics:
2.2 Product Functions is reviewed and confirm
2.6 User Documentation is reviewed and removed

Topics for second review:
2.1 Product Perspective 
2.3 User Classes and Characteristics  
2.4 Operating Environment  
2.5 Design and Implementation Constraints  
2.7 Assumptions and Dependencies

**Comment by epaceva** [comment]
Confirmed Topics:
4.2 Use Cases Related to Admin Panel
4.2.1 Use Cases Related to Dashboard
4.2.2 Use Cases Related to Pages
4.2.3 Use Cases Related to News
4.2.4  Use Cases Related to Blocks
4.2.5  Use Cases Related to Menus
4.2.6  Use Cases Related to Translation
4.2.7 Use Cases Related to Files
4.2.8  Use Cases Related to Galleries
4.2.9 Use Cases Related to Users
4.2.10 Use Cases Related to Roles

**Comment by epaceva** [comment]
Flow chars and chapters 3, 5 and 6 are uploaded and reviewed
