### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by epaceva** [TypiCMS-TeamGamayunSoftUni/Base#8]
Using template please work under Test cases regarding team project

**Comment by npnataly** [comment]
I have created test cases doc: See https://docs.google.com/spreadsheets/d/1yHTisW3ioWKI99MevLkAvQH04dsKsVq7N90mN1gjfXE/edit#gid=0

**Comment by npnataly** [comment]
Test cases about reader and admin login page are finished.

**Comment by ivamladenova** [comment]
Currently working on Admin Panel Test Cases. Dashboard test cases are completed and Pages test cases are in progress.

**Comment by npnataly** [comment]
Write tests case for options from content block.
I will the test cases about Media and Users and Roles blocks.

**Comment by npnataly** [comment]
Add some more test cases for reader

**Comment by ivamladenova** [comment]
Test cases about Dashboard, Pages, News, Blocks, Menus and Translations are completed.

**Comment by npnataly** [comment]
Files test cases are completed

**Comment by ivamladenova** [comment]
User test cases are in progress.

**Comment by ivamladenova** [comment]
User test cases are completed.

**Comment by npnataly** [comment]
Galleries test cases- Done

**Comment by npnataly** [comment]
Roles test cases- Done

**Comment by npnataly** [comment]
test cases are completed
