### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by epaceva** [TypiCMS-TeamGamayunSoftUni/Base#9]
Please work under Use Cases regarding team project. Please submit each Use Case in  [SRS](SRS_TypiCMS-TeamGamayunSoftUni.doc)

**Comment by epaceva** [comment]
Based on uploaded use case 1, use case 2 is created and uploaded to SRS

**Comment by epaceva** [comment]
Based on uploaded use case 1, use case 3 is created and uploaded to SRS

**Comment by epaceva** [comment]
Based on uploaded use case 1, use case 4 is created and uploaded to SRS

**Comment by epaceva** [comment]
Please review use cases 2 , 3 and 4.  Please correct if needed. 
I will proceed with use cases tomorrow

**Comment by ivamladenova** [comment]
I've made some changes in the format and fixed some typos in the use cases 2,3 and 4.

**Comment by nBorimechkov** [comment]
Added a few use cases, corrected small inconsistencies here and there, more use case in progress.

**Comment by epaceva** [comment]
Use cases to Blocks and Users are uploaded in SRS. Please review and if needed correct.

**Comment by epaceva** [comment]
Use cases for Dashboard; Pages; News; Menus; Files; Galleries and Roles uploaded in SRS. Please review and correct if needed.

**Comment by epaceva** [comment]
Use cases related to Translations are uploaded. Please review and correct if needed.

**Comment by epaceva** [comment]
Use cases related to Reader/View page are uploaded to SRS. Please review and correct if needed

**Comment by epaceva** [comment]
Use cases to Admin Login Page and Admin Panel Navigation Bar are uploaded. Please review and correct if needed.

**Comment by epaceva** [comment]
All related use cases were uploaded. Issue is resolved
